# Generated by Django 4.2.6 on 2023-11-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_post', '0010_likedcomments_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('contact', models.CharField(max_length=400)),
            ],
        ),
    ]
