# Generated by Django 4.2.6 on 2023-11-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_post', '0012_alter_routes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic/')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
